### ISSUE TITLE
Error while camera is already on (for android)

### ISSUE THREAD

**Issue by elibroide** [sewonist/FlashLight#3]
Thank you for the ANE (speed up my progress),
however I found that once I instantiated a FlashLight instance I couldn't use my camera object, and vice versa

I took the liberty of looking at your android source code and I see that you open the camera like so:

public FlashLightContext()
    {
        FlashLightContext.camera = Camera.open();
        FlashLightContext.parameters =        FlashLightContext.camera.getParameters();
}

From what I understand from here http://developer.android.com/training/camera/cameradirect.html,
there is a need to check if the camera is already activated by something else...
which leads me to ask: 
Can you add the flash to an already running camera?

**Comment by sewonist** [comment]
Hi elibrolde.
I'm sorry to write back that late. I've checked this issue. However I couldn't fix this issue. I thought I can't release already using camera. so I just put the make to no error. Please check new code.
Thanks
