### ISSUE TITLE
Static Instance Problem

### ISSUE THREAD

**Issue by Hanleon** [sewonist/FlashLight#4]
I actually have some problem here. The following is my plan.
I am trying to run the library output to ios phone 5, using Actionscript that you providing here. but i got some static instance problem or some come which might incorrect where need your help and guide at here. Thanks

My code in Flash cs6 Pro/ Ios 7 (iphone5)

import com.itpointlab.ane.FlashLight;
var Flashlight:FlashLight =new FlashLight();

if( Flashlight.getInstance().isSupported ){
    Flashlight.getInstance().on(); // turn on
    Flashlight.getInstance().off(); // turn off
    var mode:Boolean = Flashlight.getInstance().mode; // get torch mode
}

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Error Problem

Frame 1, Line 4 1061: Call to a possibly undefined method getInstance through a reference with static type com.itpointlab.ane:FlashLight.
Frame 1, Line 5 1061: Call to a possibly undefined method getInstance through a reference with static type com.itpointlab.ane:FlashLight.
Frame 1, Line 6 1061: Call to a possibly undefined method getInstance through a reference with static type com.itpointlab.ane:FlashLight.
Frame 1, Line 7 1061: Call to a possibly undefined method getInstance through a reference with static type com.itpointlab.ane:FlashLight.

Last, really thank u so much for guiding me here.

**Comment by sewonist** [comment]
Hi, Hanleon
I've added example project. I thought it is useful your project. Please check it.
Thanks~
